### ISSUE TITLE
.v4 generator generate same key

### ISSUE THREAD

**Issue by oyakyazilim** [Daegalus/dart-uuid#77] opened 2021-11-26 10:42 UTC
When I use your package always generate same key after second time...

**Comment by adamzemmoura** [comment] 2022-01-02 22:20
Having the same issue.  Seems to be the case when called in a loop.  Similar to old issue #8.  I objects being created in a loop and every one of them has the same id when using `Uuid().v4()`

**Comment by Daegalus** [comment] 2022-01-02 22:28
Ugh ok, I will take a look at it tonight, you would think tests to catch this would catch it but they don't apparently. Need to add new tests once I figure out why this is happening.

Thanks for the additional report. I will get to this as soon as I can.

**Comment by adamzemmoura** [comment] 2022-01-02 22:37
Thanks for the quick reply @Daegalus  but actually, you can disregard my report.  It was my mistake!  🤦🏻‍♂️   Just tested it again when I corrected my mistake and it's working as expected. Sorry for the false alarm.

**Comment by Daegalus** [comment] 2022-01-02 23:59
Ok, I will leave this open just incase there are other reports, but thanks for confirming. I have yet to find anything, so I will consider this a maybe bug until I get more reports.

**Comment by notandyvee** [comment] 2022-01-17 15:31
@adamzemmoura if you don't mind, could you post what your mistake was. I would like to use this library, but leaving something like this open doesn't improve my confidence.

**Comment by josh4500** [comment] 2022-06-11 22:12
> Ok, I will leave this open just incase there are other reports, but thanks for confirming. I have yet to find anything, so I will consider this a maybe bug until I get more reports.

I got duplicates too

**Comment by Daegalus** [comment] 2022-06-12 01:49
> > Ok, I will leave this open just incase there are other reports, but thanks for confirming. I have yet to find anything, so I will consider this a maybe bug until I get more reports.
> 
> I got duplicates too

Can you provide example code so I can reproduce it? Or how you are using the library? If I can reproduce it, I can more likely fix it. So far all reports have been incorrect usage of the library. Not saying that's the case, but an example would help. I specifically have a test that generates millions of UUIDs to test for collisions and duplicates, and it passes.

**Comment by Daegalus** [comment] 2022-11-13 09:54
I am closing this issue as 4.0.0-beta1 has a refactor/redesign of the code. If anyone encounters duplicates, please open a new issue, I have not gotten any new reports of anyone getting duplicates.

**Closed by Daegalus** 2022-11-13 09:54 UTC
Labels: needs more info
